server:
  port: 8102
  servlet:
    context-path: /config
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
#  cloud:
#    config:
#      server:
#        git: #配置存储配置信息的Git仓库
#          uri: https://gitee.com/macrozheng/springcloud-config.git
#          username: macro
#          password: 123456
#          clone-on-start: true #开启启动时直接从git获取配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
